TIBS.SAFCO.Web/Areas/Mpa/Models/Users/CreateOrEditUserModalViewModel.cs
using Abp.AutoMapper;
using System.Linq;
using TIBS.SAFCO.Authorization.Users.Dto;

namespace TIBS.SAFCO.Web.Areas.Mpa.Models.Users
{
    [AutoMapFrom(typeof (GetUserForEditOutput))]
    public class CreateOrEditUserModalViewModel : GetUserForEditOutput
    {
        public bool CanChangeUserName
        {
            get { return User.UserName != Authorization.Users.User.AdminUserName; }
        }

        public int AssignedRoleCount
        {
            get { return Roles.Count(r => r.IsAssigned); }
        }

        public bool IsEditMode
        {
            get { return User.Id.HasValue; }
        }

        public CreateOrEditUserModalViewModel(GetUserForEditOutput output)
        {
            output.MapTo(this);
        }
    }
}

TIBS.SAFCO.Web/Areas/Mpa/Models/Users/UserPermissionsEditViewModel.cs
using Abp.AutoMapper;
using TIBS.SAFCO.Authorization.Users;
using TIBS.SAFCO.Authorization.Users.Dto;
using TIBS.SAFCO.Web.Areas.Mpa.Models.Common;

namespace TIBS.SAFCO.Web.Areas.Mpa.Models.Users
{
    [AutoMapFrom(typeof(GetUserPermissionsForEditOutput))]
    public class UserPermissionsEditViewModel : GetUserPermissionsForEditOutput, IPermissionsEditViewModel
    {
        public User User { get; private set; }

        public UserPermissionsEditViewModel(GetUserPermissionsForEditOutput output, User user)
        {
            User = user;
            output.MapTo(this);
        }
    }
}

TIBS.SAFCO.Web/Areas/Mpa/Controllers/UsersController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Abp.Application.Services.Dto;
using Abp.Web.Mvc.Authorization;
using TIBS.SAFCO.Authorization;
using TIBS.SAFCO.Authorization.Users;
using TIBS.SAFCO.Web.Areas.Mpa.Models.Users;
using TIBS.SAFCO.Web.Controllers;

namespace TIBS.SAFCO.Web.Areas.Mpa.Controllers
{
    [AbpMvcAuthorize(AppPermissions.Pages_Administration_Users)]
    public class UsersController : SAFCOControllerBase
    {
        private readonly IUserAppService _userAppService;
        private readonly UserManager _userManager;

        public UsersController(IUserAppService userAppService, UserManager userManager)
        {
            _userAppService = userAppService;
            _userManager = userManager;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<PartialViewResult> CreateOrEditModal(long? id)
        {
            var output = await _userAppService.GetUserForEdit(new NullableIdInput<long> {Id = id});
            var viewModel = new CreateOrEditUserModalViewModel(output);

            return PartialView("_CreateOrEditModal", viewModel);
        }

        public async Task<PartialViewResult> PermissionsModal(long id)
        {
            var user = await _userManager.GetUserByIdAsync(id);
            var output = await _userAppService.GetUserPermissionsForEdit(new IdInput<long>(id));
            var viewModel = new UserPermissionsEditViewModel(output, user);

            return PartialView("_PermissionsModal", viewModel);
        }
    }
}

TIBS.SAFCO.Web/Controllers/ProfileController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Abp.Auditing;
using Abp.Domain.Uow;
using Abp.Extensions;
using Abp.IO.Extensions;
using Abp.Runtime.Session;
using Abp.UI;
using Abp.Web.Mvc.Authorization;
using TIBS.SAFCO.Authorization.Users;
using TIBS.SAFCO.Net.MimeTypes;
using TIBS.SAFCO.Storage;
using Abp.Domain.Repositories;
using TIBS.SAFCO.Employees;
using TIBS.SAFCO.Employees.Dto;
using Abp.Linq;
using System.Linq;
using Abp.Linq.Extensions;
using System.IO;
using TIBS.SAFCO.Companies.Dto;
using TIBS.SAFCO.EntityFramework;

namespace TIBS.SAFCO.Web.Controllers
{
    [AbpMvcAuthorize]
    public class ProfileController : SAFCOControllerBase
    {
        private readonly UserManager _userManager;
        private readonly IBinaryObjectManager _binaryObjectManager;
        private readonly IRepository<Employee> _EmployeeRepository;
        SAFCODbContext db = new SAFCODbContext();
        public ProfileController(IRepository<Employee> EmployeeRepository, UserManager userManager, IBinaryObjectManager binaryObjectManager)
        {
            _userManager = userManager;
            _binaryObjectManager = binaryObjectManager;
            _EmployeeRepository = EmployeeRepository;
        }

        [DisableAuditing]
        public async Task<FileResult> GetProfilePicture()
        {
            var user = await _userManager.GetUserByIdAsync(AbpSession.GetUserId());
            if (user.ProfilePictureId == null)
            {
                return GetDefaultProfilePicture();
            }

            return await GetProfilePictureById(user.ProfilePictureId.Value);
        }

        [DisableAuditing]
        public async Task<FileResult> GetProfilePictureById(string id = "")
        {
            if (id.IsNullOrEmpty())
            {
                return GetDefaultProfilePicture();                
            }

            return await GetProfilePictureById(Guid.Parse(id));
        }

        [UnitOfWork]
        public async virtual Task ChangeProfilePicture()
        {
            if (Request.Files.Count <= 0 || Request.Files[0] == null)
            {
                throw new UserFriendlyException(L("ProfilePicture_Change_Error"));
            }
            
            var file = Request.Files[0];

            if (file.ContentLength > 30720) //30KB.
            {
                throw new UserFriendlyException(L("ProfilePicture_Warn_SizeLimit"));
            }

            var user = await _userManager.GetUserByIdAsync(AbpSession.GetUserId());
            long userId = AbpSession.GetUserId();
            var emp = _EmployeeRepository.GetAll().Where(p=>p.UserId==userId).FirstOrDefault();
                if (Request.Files.Count <= 0 || Request.Files[0] == null)
                {
                    throw new UserFriendlyException(L("ProfilePicture_Change_Error"));
                }
               
                string filename = file.FileName;
                string path = System.Web.HttpContext.Current.Server.MapPath("~/EmployeeProfilePicture/" + emp.Id + "");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                path = Path.Combine(Server.MapPath("~/EmployeeProfilePicture/" + emp.Id + ""), filename);
                //path = Path.Combine(Server.MapPath("~/Photos"), empId + ".jpg");
                file.SaveAs(path);
                path = Url.Content(Path.Combine("/EmployeeProfilePicture/" + emp.Id + "/" + filename));
                CreateCompanyInput input = new CreateCompanyInput();


                var contactinput = db.Employees.Where(p => p.Id == emp.Id).FirstOrDefault();
                contactinput.PhotoPath = path;
                // var contactcompany = contactinput.MapTo<CompanyContact>();
                db.SaveChanges();


            //Delete old picture
            if (user.ProfilePictureId.HasValue)
            {
                await _binaryObjectManager.DeleteAsync(user.ProfilePictureId.Value);
            }

            //Save new picture
            var storedFile = new BinaryObject(file.InputStream.GetAllBytes());
            await _binaryObjectManager.SaveAsync(storedFile);
            
            //Update new picture on the user
            user.ProfilePictureId = storedFile.Id;
        }

        public FileResult GetDefaultProfilePicture()
        {
            return File(Server.MapPath("~/Common/Images/default-profile-picture.png"), MimeTypeNames.ImagePng);
        }

        public async Task<FileResult> GetProfilePictureById(Guid profilePictureId)
        {
            var file = await _binaryObjectManager.GetOrNullAsync(profilePictureId);
            if (file == null)
            {
                return GetDefaultProfilePicture();
            }

            return File(file.Bytes, MimeTypeNames.ImageJpeg);
        }
    }
}

TIBS.SAFCO.Web/Areas/Mpa/Views/Users/Index.cshtml
@using Abp.Web.Mvc.Extensions
@using TIBS.SAFCO.Authorization
@using TIBS.SAFCO.Web.Navigation
@{
    ViewBag.CurrentPageName = PageNames.App.Common.Users;
}
@section Styles
{
    @Html.IncludeStyle("~/Areas/Mpa/Views/Users/index.min.css")
}
@section Scripts
{
    @Html.IncludeScript("~/Areas/Mpa/Views/Common/_PermissionTree.js")
    @Html.IncludeScript("~/Areas/Mpa/Views/Users/_CreateOrEditModal.js")
    @Html.IncludeScript("~/Areas/Mpa/Views/Users/_PermissionsModal.js")
    @Html.IncludeScript("~/Areas/Mpa/Views/Users/Index.js")
}
<div class="row margin-bottom-5">
    <div class="col-xs-6">
        <div class="page-head">
            <div class="page-title">
                <h1>
                    <span>@L("Users")</span> <small>@L("UsersHeaderInfo")</small>
                </h1>
            </div>
        </div>
    </div>
    <div class="col-xs-6 text-right">
        <button id="ExportUsersToExcelButton" class="btn btn-default"><i class="fa fa-file-excel-o"></i> @L("ExportToExcel")</button>
        @if (IsGranted(AppPermissions.Pages_Administration_Users_Create))
        {
            <button id="CreateNewUserButton" class="btn btn-primary blue"><i class="fa fa-plus"></i> @L("CreateNewUser")</button>
        }
    </div>
</div>

<div class="portlet light">
    <div class="portlet-title portlet-title-filter">
        <div class="inputs inputs-full-width">
            <div class="portlet-input">
                <form>
                    <div class="input-group">
                        <input id="UsersTableFilter" class="form-control" placeholder="@L("SearchWithThreeDot")" type="text">
                        <span class="input-group-btn">
                            <button id="GetUsersButton" class="btn default" type="submit"><i class="icon-magnifier"></i></button>
                        </span>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="portlet-body">
        <div id="UsersTable"></div>
    </div>
</div>

TIBS.SAFCO.Web/Areas/Mpa/Views/Users/_CreateOrEditModal.cshtml
@using Abp.Extensions
@using TIBS.SAFCO.Web.Areas.Mpa.Models.Common.Modals
@model TIBS.SAFCO.Web.Areas.Mpa.Models.Users.CreateOrEditUserModalViewModel

@Html.Partial("~/Areas/Mpa/Views/Common/Modals/_ModalHeader.cshtml", new ModalHeaderViewModel(Model.IsEditMode ? (L("EditUser") + ": " + Model.User.UserName) : L("CreateNewUser")))

<div class="modal-body">

    <div class="tabbable-line">
        <ul class="nav nav-tabs ">
            <li class="active">
                <a href="#UserInformationsTab" data-toggle="tab" aria-expanded="true">
                    @L("UserInformations")
                </a>
            </li>
            <li class="">
                <a href="#RolesTab" data-toggle="tab" aria-expanded="false">
                    @L("Roles") <b class="badge badge-primary"><span id="assigned-role-count">@Model.AssignedRoleCount</span></b>
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="UserInformationsTab">

                <form name="UserInformationsForm" role="form" novalidate class="form-validation">

                    @if (Model.IsEditMode)
                    {
                        <input type="hidden" name="Id" value="@Model.User.Id" />
                    }

                    <div class="row">
                        <div class="col-sm-4 text-center">
                            @if (Model.ProfilePictureId.HasValue)
                            {
                                <img src="@Url.Action("GetProfilePictureById", "Profile", new { area = string.Empty })?id=@(Model.ProfilePictureId.Value)" width="128" height="128" class="img-thumbnail img-rounded user-edit-dialog-profile-image" />
                            }
                            else
                            {
                                <img src="@Url.Content("~/Common/Images/default-profile-picture.png")" width="128" height="128" class="img-thumbnail img-rounded user-edit-dialog-profile-image" />
                            }
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group form-md-line-input form-md-floating-label no-hint">
                                <input class="form-control@(Model.User.Name.IsNullOrEmpty() ? "" : " edited")" value="@Model.User.Name" type="text" name="Name" required maxlength="@TIBS.SAFCO.Authorization.Users.User.MaxNameLength">
                                <label>@L("Name")</label>
                            </div>

                            <div class="form-group form-md-line-input form-md-floating-label no-hint">
                                <input type="text" name="Surname" class="form-control@(Model.User.Surname.IsNullOrEmpty() ? "" : " edited")" value="@Model.User.Surname" required maxlength="@TIBS.SAFCO.Authorization.Users.User.MaxSurnameLength">
                                <label>@L("Surname")</label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group form-md-line-input form-md-floating-label no-hint">
                        <input type="email" name="EmailAddress" class="form-control@(Model.User.EmailAddress.IsNullOrEmpty() ? "" : " edited")" value="@Model.User.EmailAddress" required maxlength="@TIBS.SAFCO.Authorization.Users.User.MaxEmailAddressLength">
                        <label>@L("EmailAddress")</label>
                    </div>

                    <div class="form-group form-md-line-input form-md-floating-label">
                        <input type="text" @Html.Raw(!Model.CanChangeUserName ? "disabled=\"disabled\"" : "") name="UserName" class="form-control@(Model.User.EmailAddress.IsNullOrEmpty() ? "" : " edited")" value="@Model.User.UserName" required maxlength="@TIBS.SAFCO.Authorization.Users.User.MaxUserNameLength">
                        <label>@L("UserName")</label>
                        @if (!Model.CanChangeUserName)
                        {
                            <span class="help-block">@L("CanNotChangeAdminUserName")</span>
                        }
                    </div>

                    <div class="md-checkbox-list">
                        <div class="md-checkbox">
                            <input id="EditUser_SetRandomPassword" class="md-check" type="checkbox" name="SetRandomPassword" value="true" @Html.Raw(Model.IsEditMode ? "" : "checked=\"checked\"") />
                            <label for="EditUser_SetRandomPassword">
                                <span class="inc"></span>
                                <span class="check"></span>
                                <span class="box"></span>
                                @L("SetRandomPassword")
                            </label>
                        </div>
                    </div>

                    <div class="form-group form-md-line-input form-md-floating-label no-hint" style="@(Model.IsEditMode ? "display:block" : "display:none")">
                        <input id="EditUser_Password" type="password" name="Password" class="form-control" maxlength="@TIBS.SAFCO.Authorization.Users.User.MaxPlainPasswordLength" minlength="@TIBS.SAFCO.Authorization.Users.User.MinPlainPasswordLength">
                        <label>@L("Password")</label>
                    </div>

                    <div class="form-group form-md-line-input form-md-floating-label no-hint" style="@(Model.IsEditMode ? "display:block" : "display:none")">
                        <input type="password" name="PasswordRepeat" class="form-control" maxlength="@TIBS.SAFCO.Authorization.Users.User.MaxPlainPasswordLength" minlength="@TIBS.SAFCO.Authorization.Users.User.MinPlainPasswordLength" equalto="#EditUser_Password">
                        <label>@L("PasswordRepeat")</label>
                    </div>

                    <div class="md-checkbox-list">
                        <div class="md-checkbox">
                            <input id="EditUser_ShouldChangePasswordOnNextLogin" class="md-check" type="checkbox" name="ShouldChangePasswordOnNextLogin" value="true" @Html.Raw(Model.User.ShouldChangePasswordOnNextLogin ? "checked=\"checked\"" : "")>
                            <label for="EditUser_ShouldChangePasswordOnNextLogin">
                                <span class="inc"></span>
                                <span class="check"></span>
                                <span class="box"></span>
                                @L("ShouldChangePasswordOnNextLogin")
                            </label>
                        </div>
                        <div class="md-checkbox">
                            <input id="EditUser_SendActivationEmail" class="md-check" type="checkbox" name="SendActivationEmail" value="true" @Html.Raw(Model.IsEditMode ? "" : "checked=\"checked\"")>
                            <label for="EditUser_SendActivationEmail">
                                <span class="inc"></span>
                                <span class="check"></span>
                                <span class="box"></span>
                                @L("SendActivationEmail")
                            </label>
                        </div>
                        <div class="md-checkbox">
                            <input id="EditUser_IsActive" class="md-check" type="checkbox" name="IsActive" value="true" @Html.Raw(Model.User.IsActive ? "checked=\"checked\"" : "")>
                            <label for="EditUser_IsActive">
                                <span class="inc"></span>
                                <span class="check"></span>
                                <span class="box"></span>
                                @L("Active")
                            </label>
                        </div>
                    </div>

                </form>

            </div>
            <div class="tab-pane" id="RolesTab">

                <div class="md-checkbox-list user-role-checkbox-list">
                    @foreach (var role in Model.Roles)
                    {
                        <div class="md-checkbox">
                            <input id="EditUser_@(role.RoleName)" class="md-check" type="checkbox" name="@(role.RoleName)" value="true" @Html.Raw(role.IsAssigned ? "checked=\"checked\"" : "")>
                            <label for="EditUser_@(role.RoleName)">
                                <span class="inc"></span>
                                <span class="check"></span>
                                <span class="box"></span>
                                @role.RoleDisplayName
                            </label>
                        </div>
                    }
                </div>

            </div>
        </div>
    </div>

</div>

@Html.Partial("~/Areas/Mpa/Views/Common/Modals/_ModalFooterWithSaveAndCancel.cshtml")

TIBS.SAFCO.Web/Areas/Mpa/Views/Users/_PermissionsModal.cshtml
@using TIBS.SAFCO.Web.Areas.Mpa.Models.Common.Modals
@model TIBS.SAFCO.Web.Areas.Mpa.Models.Users.UserPermissionsEditViewModel

@Html.Partial("~/Areas/Mpa/Views/Common/Modals/_ModalHeader.cshtml", new ModalHeaderViewModel(L("Permissions") + " - " + Model.User.UserName))

<div class="modal-body">
    @Html.Partial("~/Areas/Mpa/Views/Common/_PermissionTree.cshtml", Model)
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-default pull-left reset-permissions-button" data-toggle="tooltip" title="@L("ResetPermissionsTooltip")" data-placement="top"><span>@L("ResetSpecialPermissions")</span></button>
    <button type="button" class="btn default close-button" data-dismiss="modal">@L("Cancel")</button>
    <button type="button" class="btn blue save-button"><i class="fa fa-save"></i> <span>@L("Save")</span></button>
</div>